import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  Bell,
  Bot,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CircleAlert,
  CircleCheckBig,
  CircleChevronDown,
  CircleChevronUp,
  CircleX,
  Clock4,
  CreditCard,
  Crown,
  DollarSign,
  Dot,
  Edit,
  ExternalLink,
  Eye,
  Facebook,
  FileImage,
  FileText,
  Flag,
  Heart,
  Home,
  Image,
  Instagram,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Minus,
  MoreHorizontal,
  Music2,
  PenTool,
  Play,
  Plus,
  RefreshCcw,
  RefreshCw,
  Rss,
  Save,
  Search,
  SendHorizontal,
  Settings,
  Share2,
  Shield,
  Star,
  Store,
  Target,
  ThumbsUp,
  Trash,
  Trash2,
  TrendingUp,
  Twitter,
  User,
  UserCheck,
  UserRoundX,
  Users,
  X,
  Youtube,
  Zap,
} from 'lucide-react';

export const Icons = {
  user: User,
  users: Users,
  store: Store,
  building: Building,
  building2: Building2,
  arrowRight: ArrowRight,
  logOut: LogOut,
  settings: Settings,
  barChart3: BarChart3,
  bell: Bell,
  fileText: FileText,
  home: Home,
  megaphone: Megaphone,
  search: Search,
  trendingUp: TrendingUp,
  calendar: Calendar,
  edit: Edit,
  mapPin: MapPin,
  star: Star,
  x: X,
  save: Save,
  checkCircle: CheckCircle,
  externalLink: ExternalLink,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  camera: Camera,
  eye: Eye,
  heart: Heart,
  messageCircle: MessageCircle,
  dot: Dot,
  arrowleft: ArrowLeft,
  send: SendHorizontal,
  plus: Plus,
  penTool: PenTool,
  clock4: Clock4,
  circleCheckBig: CircleCheckBig,
  circleX: CircleX,
  DollarSign: DollarSign,
  minus: Minus,
  fileImage: FileImage,
  trash: Trash,
  image: Image,
  share2: Share2,
  play: Play,
  circleAlert: CircleAlert,
  mail: Mail,
  twitter: Twitter,
  tiktok: Music2,
  refreshCcw: RefreshCcw,
  check: Check,
  circleChevronDown: CircleChevronDown,
  circleChevronUp: CircleChevronUp,
  thumbsUp: ThumbsUp,
  ban: Ban,
  moreHorizontal: MoreHorizontal,
  userCheck: UserCheck,
  flag: Flag,
  trash2: Trash2,
  alertTriangle: AlertTriangle,
  messageSquare: MessageSquare,
  crown: Crown,
  zap: Zap,
  layoutDashboard: LayoutDashboard,
  creditCard: CreditCard,
  userRoundX: UserRoundX,
  target: Target,
  shield: Shield,
  bot: Bot,
  loader2: Loader2,
  refreshCw: RefreshCw,
  rss: Rss,
};
