import {
  ArrowRight,
  BarChart3,
  Bell,
  Building,
  Building2,
  Calendar,
  Camera,
  CheckCircle,
  Edit,
  ExternalLink,
  Eye,
  Facebook,
  FileText,
  Heart,
  Home,
  Instagram,
  LogOut,
  MapPin,
  Megaphone,
  MessageCircle,
  PenTool,
  Plus,
  Save,
  Search,
  Settings,
  Star,
  Store,
  TrendingUp,
  User,
  Users,
  X,
  Youtube,
} from 'lucide-react';

export const Icons = {
  user: User,
  users: Users,
  store: Store,
  building: Building,
  building2: Building2,
  arrowRight: ArrowRight,
  logOut: LogOut,
  settings: Settings,
  barChart3: BarChart3,
  bell: Bell,
  fileText: FileText,
  home: Home,
  megaphone: Megaphone,
  search: Search,
  trendingUp: TrendingUp,
  calendar: Calendar,
  edit: Edit,
  mapPin: MapPin,
  star: Star,
  x: X,
  save: Save,
  checkCircle: CheckCircle,
  externalLink: ExternalLink,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  camera: Camera,
  eye: Eye,
  heart: Heart,
  messageCircle: MessageCircle,
  plus: Plus,
  penTool: PenTool,
};
