import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CircleAlert,
  CircleCheckBig,
  CircleX,
  Clock4,
  DollarSign,
  Dot,
  Edit,
  ExternalLink,
  Eye,
  Facebook,
  FileImage,
  FileText,
  Heart,
  Home,
  Image,
  Instagram,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Minus,
  Music2,
  PenTool,
  Play,
  Plus,
  RefreshCcw,
  Save,
  Search,
  SendHorizontal,
  Settings,
  Share2,
  Star,
  Store,
  Trash,
  TrendingUp,
  Twitter,
  User,
  Users,
  X,
  Youtube,
} from 'lucide-react';

export const Icons = {
  user: User,
  users: Users,
  store: Store,
  building: Building,
  building2: Building2,
  arrowRight: ArrowRight,
  logOut: LogOut,
  settings: Settings,
  barChart3: BarChart3,
  bell: Bell,
  fileText: FileText,
  home: Home,
  megaphone: Megaphone,
  search: Search,
  trendingUp: TrendingUp,
  calendar: Calendar,
  edit: Edit,
  mapPin: MapPin,
  star: Star,
  x: X,
  save: Save,
  checkCircle: CheckCircle,
  externalLink: ExternalLink,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  camera: Camera,
  eye: Eye,
  heart: Heart,
  messageCircle: MessageCircle,
  dot: Dot,
  arrowleft: ArrowLeft,
  send: SendHorizontal,
  plus: Plus,
  penTool: PenTool,
  clock4: Clock4,
  circleCheckBig: CircleCheckBig,
  circleX: CircleX,
  DollarSign: DollarSign,
  minus: Minus,
  fileImage: FileImage,
  trash: Trash,
  image: Image,
  share2: Share2,
  play: Play,
  circleAlert: CircleAlert,
  mail: Mail,
  twitter: Twitter,
  tiktok: Music2,
  refreshCcw: RefreshCcw,
  check: Check,
};
